// Signed: Kev + claude-fable-5, 2026-06-09
// Format: MurphySig v0.4 (https://murphysig.dev/spec)
// Prior: Unknown (new file)
//
// Context: Tests for the .murphysig declaration parser used by the
// nightly registry update. Run with: node --test scripts/
//
// Confidence: 0.85 - pure-function tests, fixtures mirror real
// declarations generated by murphysig.dev/init and bin/sig.

import { test } from "node:test";
import assert from "node:assert/strict";
import { parseMurphysig, gh, buildEntry } from "./update-registry.mjs";

const FULL = `# This Project Uses MurphySig

MurphySig is a natural language provenance convention.

## Project Details

**Primary author**: Kevin Murphy
**Convention version**: MurphySig v0.3.3
**Initialized**: 2026-01-05
`;

test("parses author, version, initialized from a full declaration", () => {
  const parsed = parseMurphysig(FULL);
  assert.equal(parsed.author, "Kevin Murphy");
  assert.equal(parsed.version, "v0.3.3");
  assert.equal(parsed.initialized, "2026-01-05");
});

test("handles missing fields without throwing", () => {
  const parsed = parseMurphysig(
    "# This Project Uses MurphySig\n\nNo details section.",
  );
  assert.equal(parsed.author, null);
  assert.equal(parsed.version, null);
  assert.equal(parsed.initialized, null);
});

test("tolerates varied spacing and bare version numbers", () => {
  const parsed = parseMurphysig(
    "**Primary author**:   Ada Lovelace\n**Convention version**: 0.4\n**Initialized**: 2026-04-21",
  );
  assert.equal(parsed.author, "Ada Lovelace");
  assert.equal(parsed.version, "v0.4");
  assert.equal(parsed.initialized, "2026-04-21");
});

// Hostile declarations: the registry ingests .murphysig files from ANY
// public repo and deploys unattended, so parsed fields must be inert even
// before the render-side escapes (site/src/lib/escape.mjs) apply.

test("rejects a version that is not a version", () => {
  const parsed = parseMurphysig(
    '**Convention version**: v0.4"/><script>alert(1)</script>',
  );
  assert.equal(parsed.version, null);
});

test("rejects an initialized value that is not a date", () => {
  const parsed = parseMurphysig("**Initialized**: </script><script>x</script>");
  assert.equal(parsed.initialized, null);
});

test("strips control characters and line separators from author", () => {
  const parsed = parseMurphysig("**Primary author**: Ada\u0000\u001b[31m\u2028Lovelace\u0085");
  assert.equal(parsed.author, "Ada[31mLovelace");
});

test("caps author length", () => {
  const parsed = parseMurphysig(`**Primary author**: ${"A".repeat(500)}`);
  assert.equal(parsed.author.length, 100);
});

// GitHub code search allows ~10 req/min; a 429 used to kill the whole
// nightly run (2026-10-05 and -06). gh() now backs off and retries.

const reply = (status, body, headers = {}) => ({
  ok: status >= 200 && status < 300,
  status,
  headers: { get: (k) => headers[k.toLowerCase()] ?? null },
  json: async () => body,
  text: async () => (typeof body === "string" ? body : JSON.stringify(body)),
});

test("gh retries a 429 after the advertised wait", async () => {
  const replies = [
    reply(429, '{"message":"try again in 2.332055904s"}'),
    reply(200, { ok: true }),
  ];
  const slept = [];
  const out = await gh("/search/code?q=x", "t", {
    fetch: async () => replies.shift(),
    sleep: async (ms) => slept.push(ms),
  });
  assert.deepEqual(out, { ok: true });
  assert.equal(slept.length, 1);
  assert.ok(slept[0] >= 2333 && slept[0] < 10_000, `slept ${slept[0]}`);
});

test("gh honours Retry-After on a secondary rate limit (403)", async () => {
  const replies = [
    reply(403, "secondary rate limit", { "retry-after": "7" }),
    reply(200, { ok: 1 }),
  ];
  const slept = [];
  await gh("/x", "t", { fetch: async () => replies.shift(), sleep: async (ms) => slept.push(ms) });
  assert.deepEqual(slept, [7000]);
});

test("gh gives up after maxAttempts", async () => {
  let calls = 0;
  await assert.rejects(
    gh("/x", "t", {
      fetch: async () => (calls++, reply(429, "try again in 1s")),
      sleep: async () => {},
      maxAttempts: 3,
    }),
    /429/,
  );
  assert.equal(calls, 3);
});

test("gh does not retry a plain 404", async () => {
  let calls = 0;
  await assert.rejects(
    gh("/x", "t", { fetch: async () => (calls++, reply(404, "Not Found")), sleep: async () => {} }),
    /404/,
  );
  assert.equal(calls, 1);
});

// Review-fold (security-auditor, 2026-10-06): bound what a stranger's repo
// can push into main, and check the identifiers that become URLs and paths.

const DECL = "**Primary author**: Ada\n**Convention version**: 0.4\n**Initialized**: 2026-04-21\n";
const repoMeta = (over = {}) => ({
  private: false,
  html_url: "https://github.com/ada/engine",
  description: "Analytical",
  pushed_at: "2026-10-01T00:00:00Z",
  ...over,
});

test("buildEntry builds a normal entry", () => {
  const e = buildEntry("ada/engine", DECL, repoMeta());
  assert.equal(e.owner, "ada");
  assert.equal(e.repo, "engine");
  assert.equal(e.version, "v0.4");
  assert.equal(e.declaration, DECL);
});

test("buildEntry skips private repos", () => {
  assert.equal(buildEntry("ada/engine", DECL, repoMeta({ private: true })), null);
});

test("buildEntry skips oversized declarations instead of committing them", () => {
  assert.equal(buildEntry("ada/engine", DECL + "x".repeat(25_000), repoMeta()), null);
});

test("buildEntry rejects names that are not plain GitHub owner/repo", () => {
  for (const bad of ["ada/..", "ada/.", "../etc", "ada/engine/x", "ad a/engine", "ada.x/engine"]) {
    assert.equal(buildEntry(bad, DECL, repoMeta()), null, bad);
  }
});

test("buildEntry rejects a non-GitHub html_url", () => {
  assert.equal(buildEntry("ada/engine", DECL, repoMeta({ html_url: "javascript:alert(1)" })), null);
  assert.equal(buildEntry("ada/engine", DECL, repoMeta({ html_url: "https://evil.example/ada/engine" })), null);
});

test("buildEntry sanitises and caps the description", () => {
  const e = buildEntry("ada/engine", DECL, repoMeta({ description: "a\u202eb\u200bc\u0007" + "d".repeat(400) }));
  assert.ok(!/[\u202e\u200b\u0007]/.test(e.description));
  assert.equal(e.description.length, 300);
});

test("author loses bidi overrides and zero-width characters", () => {
  const parsed = parseMurphysig("**Primary author**: \u202eAda\u2066\u200d Lovelace\ufeff");
  assert.equal(parsed.author, "Ada Lovelace");
});

test("gh passes an abort timeout to fetch", async () => {
  let seen;
  await gh("/x", "t", { fetch: async (_u, init) => ((seen = init), reply(200, {})), sleep: async () => {} });
  assert.ok(seen.signal instanceof AbortSignal);
});

test("gh refuses to sleep for an absurd Retry-After", async () => {
  await assert.rejects(
    gh("/x", "t", {
      fetch: async () => reply(429, "slow down", { "retry-after": "86400" }),
      sleep: async () => {},
    }),
    /Retry-After/i,
  );
});
