// Signed: Kev + claude-fable-5, 2026-06-09
// Format: MurphySig v0.4 (https://murphysig.dev/spec)
// Prior: Unknown (new file)
//
// Context: Tests for the .murphysig declaration parser used by the
// nightly registry update. Run with: node --test scripts/
//
// Confidence: 0.85 - pure-function tests, fixtures mirror real
// declarations generated by murphysig.dev/init and bin/sig.

import { test } from "node:test";
import assert from "node:assert/strict";
import { parseMurphysig } from "./update-registry.mjs";

const FULL = `# This Project Uses MurphySig

MurphySig is a natural language provenance convention.

## Project Details

**Primary author**: Kevin Murphy
**Convention version**: MurphySig v0.3.3
**Initialized**: 2026-01-05
`;

test("parses author, version, initialized from a full declaration", () => {
  const parsed = parseMurphysig(FULL);
  assert.equal(parsed.author, "Kevin Murphy");
  assert.equal(parsed.version, "v0.3.3");
  assert.equal(parsed.initialized, "2026-01-05");
});

test("handles missing fields without throwing", () => {
  const parsed = parseMurphysig(
    "# This Project Uses MurphySig\n\nNo details section.",
  );
  assert.equal(parsed.author, null);
  assert.equal(parsed.version, null);
  assert.equal(parsed.initialized, null);
});

test("tolerates varied spacing and bare version numbers", () => {
  const parsed = parseMurphysig(
    "**Primary author**:   Ada Lovelace\n**Convention version**: 0.4\n**Initialized**: 2026-04-21",
  );
  assert.equal(parsed.author, "Ada Lovelace");
  assert.equal(parsed.version, "v0.4");
  assert.equal(parsed.initialized, "2026-04-21");
});
